// flow-typed signature: 1cfbdb7c955e7fcb87ccfb5bccb7605b
// flow-typed version: <<STUB>>/react-router-addons-controlled_v^0.0.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-addons-controlled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-addons-controlled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-addons-controlled/ControlledBrowserRouter' {
  declare module.exports: any;
}

declare module 'react-router-addons-controlled/ControlledHistory' {
  declare module.exports: any;
}

declare module 'react-router-addons-controlled/ControlledMemoryRouter' {
  declare module.exports: any;
}

declare module 'react-router-addons-controlled/manual-tests/index' {
  declare module.exports: any;
}

declare module 'react-router-addons-controlled/redux-example/index' {
  declare module.exports: any;
}

declare module 'react-router-addons-controlled/umd/react-history' {
  declare module.exports: any;
}

declare module 'react-router-addons-controlled/umd/react-history.min' {
  declare module.exports: any;
}

declare module 'react-router-addons-controlled/umd/react-router-addons-controlled' {
  declare module.exports: any;
}

declare module 'react-router-addons-controlled/umd/react-router-addons-controlled.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-addons-controlled/ControlledBrowserRouter.js' {
  declare module.exports: $Exports<'react-router-addons-controlled/ControlledBrowserRouter'>;
}
declare module 'react-router-addons-controlled/ControlledHistory.js' {
  declare module.exports: $Exports<'react-router-addons-controlled/ControlledHistory'>;
}
declare module 'react-router-addons-controlled/ControlledMemoryRouter.js' {
  declare module.exports: $Exports<'react-router-addons-controlled/ControlledMemoryRouter'>;
}
declare module 'react-router-addons-controlled/index' {
  declare module.exports: $Exports<'react-router-addons-controlled'>;
}
declare module 'react-router-addons-controlled/index.js' {
  declare module.exports: $Exports<'react-router-addons-controlled'>;
}
declare module 'react-router-addons-controlled/manual-tests/index.js' {
  declare module.exports: $Exports<'react-router-addons-controlled/manual-tests/index'>;
}
declare module 'react-router-addons-controlled/redux-example/index.js' {
  declare module.exports: $Exports<'react-router-addons-controlled/redux-example/index'>;
}
declare module 'react-router-addons-controlled/umd/react-history.js' {
  declare module.exports: $Exports<'react-router-addons-controlled/umd/react-history'>;
}
declare module 'react-router-addons-controlled/umd/react-history.min.js' {
  declare module.exports: $Exports<'react-router-addons-controlled/umd/react-history.min'>;
}
declare module 'react-router-addons-controlled/umd/react-router-addons-controlled.js' {
  declare module.exports: $Exports<'react-router-addons-controlled/umd/react-router-addons-controlled'>;
}
declare module 'react-router-addons-controlled/umd/react-router-addons-controlled.min.js' {
  declare module.exports: $Exports<'react-router-addons-controlled/umd/react-router-addons-controlled.min'>;
}
