// flow-typed signature: 7069ad2aba6492a542e9433d9e5ed78c
// flow-typed version: <<STUB>>/styletron-utils_v^2.2.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styletron-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'styletron-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styletron-utils/lib/hyphenate-style-name' {
  declare module.exports: any;
}

declare module 'styletron-utils/lib/index' {
  declare module.exports: any;
}

declare module 'styletron-utils/lib/inject-style-prefixed' {
  declare module.exports: any;
}

declare module 'styletron-utils/lib/inject-style' {
  declare module.exports: any;
}

declare module 'styletron-utils/lib/inject-true-prefixed' {
  declare module.exports: any;
}

declare module 'styletron-utils/lib/shorthand-map' {
  declare module.exports: any;
}

declare module 'styletron-utils/lib/test/index' {
  declare module.exports: any;
}

declare module 'styletron-utils/lib/warn-mixed-properties' {
  declare module.exports: any;
}

declare module 'styletron-utils/src/hyphenate-style-name' {
  declare module.exports: any;
}

declare module 'styletron-utils/src/index' {
  declare module.exports: any;
}

declare module 'styletron-utils/src/inject-style-prefixed' {
  declare module.exports: any;
}

declare module 'styletron-utils/src/inject-style' {
  declare module.exports: any;
}

declare module 'styletron-utils/src/shorthand-map' {
  declare module.exports: any;
}

declare module 'styletron-utils/src/test/index' {
  declare module.exports: any;
}

declare module 'styletron-utils/src/warn-mixed-properties' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styletron-utils/lib/hyphenate-style-name.js' {
  declare module.exports: $Exports<'styletron-utils/lib/hyphenate-style-name'>;
}
declare module 'styletron-utils/lib/index.js' {
  declare module.exports: $Exports<'styletron-utils/lib/index'>;
}
declare module 'styletron-utils/lib/inject-style-prefixed.js' {
  declare module.exports: $Exports<'styletron-utils/lib/inject-style-prefixed'>;
}
declare module 'styletron-utils/lib/inject-style.js' {
  declare module.exports: $Exports<'styletron-utils/lib/inject-style'>;
}
declare module 'styletron-utils/lib/inject-true-prefixed.js' {
  declare module.exports: $Exports<'styletron-utils/lib/inject-true-prefixed'>;
}
declare module 'styletron-utils/lib/shorthand-map.js' {
  declare module.exports: $Exports<'styletron-utils/lib/shorthand-map'>;
}
declare module 'styletron-utils/lib/test/index.js' {
  declare module.exports: $Exports<'styletron-utils/lib/test/index'>;
}
declare module 'styletron-utils/lib/warn-mixed-properties.js' {
  declare module.exports: $Exports<'styletron-utils/lib/warn-mixed-properties'>;
}
declare module 'styletron-utils/src/hyphenate-style-name.js' {
  declare module.exports: $Exports<'styletron-utils/src/hyphenate-style-name'>;
}
declare module 'styletron-utils/src/index.js' {
  declare module.exports: $Exports<'styletron-utils/src/index'>;
}
declare module 'styletron-utils/src/inject-style-prefixed.js' {
  declare module.exports: $Exports<'styletron-utils/src/inject-style-prefixed'>;
}
declare module 'styletron-utils/src/inject-style.js' {
  declare module.exports: $Exports<'styletron-utils/src/inject-style'>;
}
declare module 'styletron-utils/src/shorthand-map.js' {
  declare module.exports: $Exports<'styletron-utils/src/shorthand-map'>;
}
declare module 'styletron-utils/src/test/index.js' {
  declare module.exports: $Exports<'styletron-utils/src/test/index'>;
}
declare module 'styletron-utils/src/warn-mixed-properties.js' {
  declare module.exports: $Exports<'styletron-utils/src/warn-mixed-properties'>;
}
