// flow-typed signature: 3d0c6cbf478d97bae934cee16c4f4299
// flow-typed version: <<STUB>>/styletron-client_v^2.2.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styletron-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'styletron-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styletron-client/lib/styletron-client' {
  declare module.exports: any;
}

declare module 'styletron-client/lib/test/browser' {
  declare module.exports: any;
}

declare module 'styletron-client/src/styletron-client' {
  declare module.exports: any;
}

declare module 'styletron-client/src/test/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styletron-client/lib/styletron-client.js' {
  declare module.exports: $Exports<'styletron-client/lib/styletron-client'>;
}
declare module 'styletron-client/lib/test/browser.js' {
  declare module.exports: $Exports<'styletron-client/lib/test/browser'>;
}
declare module 'styletron-client/src/styletron-client.js' {
  declare module.exports: $Exports<'styletron-client/src/styletron-client'>;
}
declare module 'styletron-client/src/test/browser.js' {
  declare module.exports: $Exports<'styletron-client/src/test/browser'>;
}
